server:
  port: 9100
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# 服务名称
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mober_sun/springCloud-config-server.git
          username: mober_sun@163.com
          password: hui5657589988
          timeout: 5
          default-label: master
